<br><br>
<font size='6'><b>Exercise for Artificial Neural Networks
</b></font><br><br>

<br>
<div class=pull-right>
By Prof. Seungchul Lee<br>
http://iai.postech.ac.kr/<br>
Industrial AI Lab at POSTECH
</div>

Table of Contents
<div id="toc"></div>

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
import pandas as pd

c:\users\iai_yunseob\appdata\local\programs\python\python36\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
c:\users\iai_yunseob\appdata\local\programs\python\python36\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
c:\users\iai_yunseob\appdata\local\programs\python\python36\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
c

# Problem Definition

__<font size = 4>Steel Plates Faults Dataset</font><br>__
<font size = 2>
- Input: 27 features (Attributes)
- Output: 7 classes (7 Types of Steel Plates Faults) 
</font>

<img src='.\image_files\steel_plate_faults_description.png' width = 1000>

# Load Data

In [2]:
df = pd.read_csv('./data_files/BigML_Steel_Plates_Faults.csv')
df.head()

X_Minimum  X_Maximum  Y_Minimum  Y_Maximum  Pixels_Areas  X_Perimeter  \
0         42         50     270900     270944           267           17   
1        645        651    2538079    2538108           108           10   
2        829        835    1553913    1553931            71            8   
3        853        860     369370     369415           176           13   
4       1289       1306     498078     498335          2409           60   

   Y_Perimeter  Sum_of_Luminosity  Minimum_of_Luminosity  \
0           44              24220                     76   
1           30              11397                     84   
2           19               7972                     99   
3           45              18996                     99   
4          260             246930                     37   

   Maximum_of_Luminosity  ...  Edges_X_Index  Edges_Y_Index  \
0                    108  ...         0.4706         1.0000   
1                    123  ...         0.6000         0.9667   
2                    125  ...         0.7500         0.9474   
3                    126  ...         0.5385         1.0000   
4                    126  ...         0.2833         0.9885   

   Outside_Global_Index  LogOfAreas  Log_X_Index  Log_Y_Index  \
0                   1.0      2.4265       0.9031       1.6435   
1                   1.0      2.0334       0.7782       1.4624   
2                   1.0      1.8513       0.7782       1.2553   
3                   1.0      2.2455       0.8451       1.6532   
4                   1.0      3.3818       1.2305       2.4099   

   Orientation_Index  Luminosity_Index  SigmoidOfAreas   Fault  
0             0.8182           -0.2913          0.5822  Pastry  
1             0.7931           -0.1756          0.2984  Pastry  
2             0.6667           -0.1228          0.2150  Pastry  
3             0.8444           -0.1568          0.5212  Pastry  
4             0.9338           -0.1992          1.0000  Pastry  

[5 rows x 28 columns]

In [3]:
col = df.columns
col

Index(['X_Minimum', 'X_Maximum', 'Y_Minimum', 'Y_Maximum', 'Pixels_Areas',
       'X_Perimeter', 'Y_Perimeter', 'Sum_of_Luminosity',
       'Minimum_of_Luminosity', 'Maximum_of_Luminosity', 'Length_of_Conveyer',
       'TypeOfSteel_A300', 'TypeOfSteel_A400', 'Steel_Plate_Thickness',
       'Edges_Index', 'Empty_Index', 'Square_Index', 'Outside_X_Index',
       'Edges_X_Index', 'Edges_Y_Index', 'Outside_Global_Index', 'LogOfAreas',
       'Log_X_Index', 'Log_Y_Index', 'Orientation_Index', 'Luminosity_Index',
       'SigmoidOfAreas', 'Fault'],
      dtype='object')

In [4]:
X = df[col].drop('Fault', 1)
Y = df['Fault']

# Data preprocessing

## Normalization 

In [5]:
X

X_Minimum  X_Maximum  Y_Minimum  Y_Maximum  Pixels_Areas  X_Perimeter  \
0            42         50     270900     270944           267           17   
1           645        651    2538079    2538108           108           10   
2           829        835    1553913    1553931            71            8   
3           853        860     369370     369415           176           13   
4          1289       1306     498078     498335          2409           60   
...         ...        ...        ...        ...           ...          ...   
1936        249        277     325780     325796           273           54   
1937        144        175     340581     340598           287           44   
1938        145        174     386779     386794           292           40   
1939        137        170     422497     422528           419           97   
1940       1261       1281      87951      87967           103           26   

      Y_Perimeter  Sum_of_Luminosity  Minimum_of_Luminosity  \
0              44              24220                     76   
1              30              11397                     84   
2              19               7972                     99   
3              45              18996                     99   
4             260             246930                     37   
...           ...                ...                    ...   
1936           22              35033                    119   
1937           24              34599                    112   
1938           22              37572                    120   
1939           47              52715                    117   
1940           22              11682                    101   

      Maximum_of_Luminosity  ...  Outside_X_Index  Edges_X_Index  \
0                       108  ...           0.0047         0.4706   
1                       123  ...           0.0036         0.6000   
2                       125  ...           0.0037         0.7500   
3                       126  ...           0.0052         0.5385   
4                       126  ...           0.0126         0.2833   
...                     ...  ...              ...            ...   
1936                    141  ...           0.0206         0.5185   
1937                    133  ...           0.0228         0.7046   
1938                    140  ...           0.0213         0.7250   
1939                    140  ...           0.0243         0.3402   
1940                    133  ...           0.0147         0.7692   

      Edges_Y_Index  Outside_Global_Index  LogOfAreas  Log_X_Index  \
0            1.0000                   1.0      2.4265       0.9031   
1            0.9667                   1.0      2.0334       0.7782   
2            0.9474                   1.0      1.8513       0.7782   
3            1.0000                   1.0      2.2455       0.8451   
4            0.9885                   1.0      3.3818       1.2305   
...             ...                   ...         ...          ...   
1936         0.7273                   0.0      2.4362       1.4472   
1937         0.7083                   0.0      2.4579       1.4914   
1938         0.6818                   0.0      2.4654       1.4624   
1939         0.6596                   0.0      2.6222       1.5185   
1940         0.7273                   0.0      2.0128       1.3010   

      Log_Y_Index  Orientation_Index  Luminosity_Index  SigmoidOfAreas  
0          1.6435             0.8182           -0.2913          0.5822  
1          1.4624             0.7931           -0.1756          0.2984  
2          1.2553             0.6667           -0.1228          0.2150  
3          1.6532             0.8444           -0.1568          0.5212  
4          2.4099             0.9338           -0.1992          1.0000  
...           ...                ...               ...             ...  
1936       1.2041            -0.4286            0.0026          0.7254  
1937       1.2305            -0.4516           -0.0582    

In [6]:
display(X.describe(include = 'all'))

X_Minimum    X_Maximum     Y_Minimum     Y_Maximum   Pixels_Areas  \
count   1941.000000  1941.000000  1.941000e+03  1.941000e+03    1941.000000   
unique          NaN          NaN           NaN           NaN            NaN   
top             NaN          NaN           NaN           NaN            NaN   
freq            NaN          NaN           NaN           NaN            NaN   
mean     571.136012   617.964451  1.650685e+06  1.650739e+06    1893.878413   
std      520.690671   497.627410  1.774578e+06  1.774590e+06    5168.459560   
min        0.000000     4.000000  6.712000e+03  6.724000e+03       2.000000   
25%       51.000000   192.000000  4.712530e+05  4.712810e+05      84.000000   
50%      435.000000   467.000000  1.204128e+06  1.204136e+06     174.000000   
75%     1053.000000  1072.000000  2.183073e+06  2.183084e+06     822.000000   
max     1705.000000  1713.000000  1.298766e+07  1.298769e+07  152655.000000   

         X_Perimeter   Y_Perimeter  Sum_of_Luminosity  Minimum_of_Luminosity  \
count    1941.000000   1941.000000       1.941000e+03            1941.000000   
unique           NaN           NaN                NaN                    NaN   
top              NaN           NaN                NaN                    NaN   
freq             NaN           NaN                NaN                    NaN   
mean      111.855229     82.965997       2.063121e+05              84.548686   
std       301.209187    426.482879       5.122936e+05              32.134276   
min         2.000000      1.000000       2.500000e+02               0.000000   
25%        15.000000     13.000000       9.522000e+03              63.000000   
50%        26.000000     25.000000       1.920200e+04              90.000000   
75%        84.000000     83.000000       8.301100e+04             106.000000   
max     10449.000000  18152.000000       1.159141e+07             203.000000   

        Maximum_of_Luminosity  ...  Outside_X_Index Edges_X_Index  \
count             1941.000000  ...      1941.000000   1941.000000   
unique                    NaN  ...              NaN           NaN   
top                       NaN  ...              NaN           NaN   
freq                      NaN  ...              NaN           NaN   
mean               130.193715  ...         0.033361      0.610529   
std                 18.690992  ...         0.058961      0.243277   
min                 37.000000  ...         0.001500      0.014400   
25%                124.000000  ...         0.006600      0.411800   
50%                127.000000  ...         0.010100      0.636400   
75%                140.000000  ...         0.023500      0.800000   
max                253.000000  ...         0.875900      1.000000   

       Edges_Y_Index  Outside_Global_Index   LogOfAreas  Log_X_Index  \
count    1941.000000           1941.000000  1941.000000  1941.000000   
unique           NaN                   NaN          NaN          NaN   
top              NaN                   NaN          NaN          NaN   
freq             NaN                   NaN          NaN          NaN   
mean        0.813472              0.575734     2.492388     1.335686   
std         0.234274              0.482352     0.788930     0.481612   
min         0.048400              0.000000     0.301000     0.301000   
25%         0.596800              0.000000     1.924300     1.000000   
50%         0.947400              1.000000     2.240600     1.176100   
75%         1.000000              1.000000     2.914900     1.518500   
max         1.000000              1.000000     5.183700     3.074100   

        Log_Y_Index  Orientation_Index  Luminosity_Index  SigmoidOfAreas  
count   1941.000000        1941.000000       1941.000000     1941.000000  
unique          NaN                NaN               NaN             NaN  
top             NaN                NaN               NaN             NaN  
freq            NaN                NaN               NaN             NaN  
mean       1.403271           0

In [7]:
x_np = np.asarray(X)

In [8]:
x_np

array([[42, 50, 270900, ..., 0.8182, -0.2913, 0.5822],
       [645, 651, 2538079, ..., 0.7931, -0.1756, 0.2984],
       [829, 835, 1553913, ..., 0.6667, -0.1228, 0.215],
       ...,
       [145, 174, 386779, ..., -0.4828, 0.0052, 0.7079],
       [137, 170, 422497, ..., -0.0606, -0.0171, 0.9919],
       [1261, 1281, 87951, ..., -0.2, -0.1139, 0.5296]], dtype=object)

In [9]:
x_norm = x_np.copy()

x_min = np.min(x_norm, axis = 0)
x_norm = np.subtract(x_norm, x_min)

In [10]:
x_np

array([[42, 50, 270900, ..., 0.8182, -0.2913, 0.5822],
       [645, 651, 2538079, ..., 0.7931, -0.1756, 0.2984],
       [829, 835, 1553913, ..., 0.6667, -0.1228, 0.215],
       ...,
       [145, 174, 386779, ..., -0.4828, 0.0052, 0.7079],
       [137, 170, 422497, ..., -0.0606, -0.0171, 0.9919],
       [1261, 1281, 87951, ..., -0.2, -0.1139, 0.5296]], dtype=object)

In [11]:
x_min

array([0, 4, 6712, 6724, 2, 2, 1, 250, 0, 37, 1227, False, False, 40, 0.0,
       0.0, 0.0083, 0.0015, 0.0144, 0.0484, 0.0, 0.301, 0.301, 0.0,
       -0.991, -0.9989, 0.11900000000000001], dtype=object)

In [12]:
x_norm

array([[42, 46, 264188, ..., 1.8092000000000001, 0.7076,
        0.46320000000000006],
       [645, 647, 2531367, ..., 1.7841, 0.8233, 0.1794],
       [829, 831, 1547201, ..., 1.6577, 0.8761, 0.09599999999999999],
       ...,
       [145, 170, 380067, ..., 0.5082, 1.0041, 0.5889],
       [137, 166, 415785, ..., 0.9304, 0.9818, 0.8729],
       [1261, 1277, 81239, ..., 0.7909999999999999, 0.885,
        0.41059999999999997]], dtype=object)

In [13]:
x_max = np.max(x_norm, axis = 0)
x_norm /= (1.2*x_max)

In [14]:
x_max

array([1705, 1709, 12980949, 12980968, 152653, 10447, 18151, 11591164,
       203, 216, 567, 1, 1, 260, 0.9952, 0.9439, 0.9917,
       0.8744000000000001, 0.9856, 0.9516, 1.0, 4.8827, 2.7731, 4.2587,
       1.9827, 1.641, 0.881], dtype=object)

In [15]:
(1.2*x_max)

array([2046.0, 2050.7999999999997, 15577138.799999999, 15577161.6,
       183183.6, 12536.4, 21781.2, 13909396.799999999, 243.6, 259.2,
       680.4, 1.2, 1.2, 312.0, 1.19424, 1.13268, 1.19004, 1.04928,
       1.18272, 1.14192, 1.2, 5.85924, 3.32772, 5.11044, 2.37924,
       1.9691999999999998, 1.0572], dtype=object)

In [16]:
x_norm

array([[0.020527859237536656, 0.022430271113711726, 0.016959982407038707,
        ..., 0.7604108875102975, 0.3593337395896811, 0.4381384790011352],
       [0.3152492668621701, 0.3154866393602497, 0.1625052605938133, ...,
        0.7498613002471378, 0.4180885638838107, 0.16969353007945517],
       [0.4051808406647116, 0.4052077238150966, 0.09932510840822707, ...,
        0.6967350918780788, 0.4449014828356693, 0.09080590238365494],
       ...,
       [0.07086999022482894, 0.08289448020284768, 0.02439902506357586,
        ..., 0.21359761940787816, 0.5099024984765387, 0.5570374574347333],
       [0.06695992179863147, 0.08094402184513362, 0.02669200071581824,
        ..., 0.39104924261528895, 0.498578102782856, 0.8256715853197125],
       [0.6163245356793744, 0.6226838307002146, 0.005215270984168159,
        ..., 0.3324591045880197, 0.4494210847044485, 0.38838441165342413]],
      dtype=object)

In [17]:
np.max(x_norm)

0.8333333333333335

In [18]:
x_norm.shape

(1941, 27)

## One-Hot Encoding

In [19]:
Y

0             Pastry
1             Pastry
2             Pastry
3             Pastry
4             Pastry
            ...     
1936    Other_Faults
1937    Other_Faults
1938    Other_Faults
1939    Other_Faults
1940    Other_Faults
Name: Fault, Length: 1941, dtype: object

In [20]:
labels = list(np.unique(Y))
labels

['Bumps',
 'Dirtiness',
 'K_Scatch',
 'Other_Faults',
 'Pastry',
 'Stains',
 'Z_Scratch']

In [21]:
label_dict = {}

for i, l in zip(range(len(labels)), labels):
    label_dict[l] = i
    
label_dict

{'Bumps': 0,
 'Dirtiness': 1,
 'K_Scatch': 2,
 'Other_Faults': 3,
 'Pastry': 4,
 'Stains': 5,
 'Z_Scratch': 6}

In [22]:
y_class = np.zeros(Y.shape)

for i in range(len(Y)):
    y_class[i] =  label_dict[Y[i]]

In [23]:
y_class

array([4., 4., 4., ..., 3., 3., 3.])

In [24]:
def one_hot_encoding(y):
    y_ = np.zeros([len(y), np.max(y) + 1])
    for i in range(len(y)):
        y_[i, y[i]] = 1  
    return y_.astype('uint8')

In [25]:
y_ohe = one_hot_encoding(y_class.astype('uint8'))

In [26]:
y_ohe

array([[0, 0, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 1, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [27]:
y_ohe.shape

(1941, 7)

# ANN Model

## 0. Base model

In [ ]:
n_input = ??
n_hidden1 = ??
n_hidden2 = ??
n_output = ??

In [ ]:
tf.reset_default_graph()

weights = {
    'hidden1' : tf.Variable(tf.random_normal([n_input, n_hidden1], stddev = 0.1)),
    'hidden2' : tf.Variable(tf.random_normal([n_hidden1, n_hidden2], stddev = 0.1)),
    'output' : tf.Variable(tf.random_normal([n_hidden2, n_output], stddev = 0.1))
}

biases = {
    'hidden1' : tf.Variable(tf.random_normal([n_hidden1], stddev = 0.1)),
    'hidden2' : tf.Variable(tf.random_normal([n_hidden2], stddev = 0.1)),
    'output' : tf.Variable(tf.random_normal([n_output], stddev = 0.1))
}

x = tf.placeholder(tf.float32, [None, n_input])
y = tf.placeholder(tf.float32, [None, n_output])
lr = tf.placeholder(tf.float32)

In [ ]:
# Define Network
def base_model(x, weights, biases):
        
    """
    build your own model
    
    
    
    """
    
    return output

pred = base_model(x, weights, biases)
loss = tf.nn.softmax_cross_entropy_with_logits_v2(logits = pred, labels = y)
loss = tf.reduce_mean(loss)
optm = tf.train.AdamOptimizer(lr).minimize(loss)

In [ ]:
# train_valid_split
def train_valid_split(x, y, test_rate = 0.2):
    v_idx = np.random.choice(len(x), size = int(len(x)*test_rate), replace = False)
    t_idx = np.setdiff1d(np.arange(len(x)), v_idx)
    return x[t_idx], y[t_idx], x[v_idx], y[v_idx]

# for minibatch gradient descent
def minibatch(x, y, batch_size = None):
    idx = np.random.choice(len(x), batch_size, replace=False)
    return x[idx], y[idx]

## 1. Not normalized VS Normalized (Input Scaling)

<img src='.\image_files\normalization_for_gd.png' width = 1000>

In [ ]:
train_X, train_Y, valid_X, valid_Y = train_valid_split(x_np, y_ohe)

In [ ]:
train_X_n, train_Y_n, valid_X_n, valid_Y_n = train_valid_split(x_norm, y_ohe)

In [ ]:
n_batch = ??    # Batch Size
n_iter = ??   # Learning Iteration
n_prt = 100    # Print Cycle
LR = ??

In [ ]:
%%time

init = tf.global_variables_initializer()
sess = tf.Session()
sess.run(init)

loss_record_train, accr_record_train = [], []

"""
train your base model with the not-normalized input
"""
for epoch in range(n_iter):
    train_x, train_y = minibatch(train_X, train_Y, n_batch)
    sess.run(??, feed_dict = {x: train_x, y: train_y, lr: LR}) 
    
    if epoch % n_prt == 0:        

        
        
        
        
        
        
        loss_record_train.append(cost)
        accr_record_train.append(accr)
        
        print ("Iter {:05d} || train_loss: {:.4f} || train_accr: {:.2f}%".format(epoch, cost, 100*accr))

In [ ]:
%%time

sess = tf.Session()
sess.run(init)

loss_n_record_train, accr_n_record_train = [], []

"""
train your base model with the normalized input
"""
for epoch in range(n_iter):
    train_x, train_y = minibatch(train_X_n, train_Y_n, n_batch)

    
    if epoch % n_prt == 0:        

        
        
        
        
        loss_n_record_train.append(cost), accr_n_record_train.append(accr)
        
        print ("Iter {:05d} || train_loss: {:.4f} || train_accr: {:.2f}%".format(epoch, cost, 100*accr))

In [ ]:
not_n_alpha = 1
n_alpha = 1

plt.figure(figsize=(10,8))
plt.plot(np.arange(len(loss_record_train))*n_prt, loss_record_train, 'k-', alpha = not_n_alpha, label = 'Not normalized')
plt.plot(np.arange(len(loss_n_record_train))*n_prt, loss_n_record_train, 'b-', alpha = n_alpha,  label = 'Normalilzed')
plt.xlabel('Iteration', fontsize = 15)
plt.ylabel('Loss', fontsize = 15)
plt.ylim([0, 5])
plt.legend(fontsize = 12)
plt.show()
plt.figure(figsize=(10,8))
plt.plot(np.arange(len(accr_record_train))*n_prt, accr_record_train, 'k-', alpha = not_n_alpha, label = 'Not normalized')
plt.plot(np.arange(len(accr_n_record_train))*n_prt, accr_n_record_train, 'b-', alpha = n_alpha,  label = 'Normalilzed')
plt.xlabel('Iteration', fontsize = 15)
plt.ylabel('Accuracy', fontsize = 15)
plt.legend(fontsize = 12)
plt.show()

## 2. Batch Normalization (Feature Scaling)

<img src='.\image_files\batch_normalization.png' width = 1000>

In [ ]:
is_training = tf.placeholder(tf.bool) # BN

def BN_model(x, weights, biases, is_training):
    
    """
    build your own BN model
    
    
    
    """
    
    return output

BN_pred = BN_model(x, weights, biases, is_training)
BN_loss = tf.nn.softmax_cross_entropy_with_logits_v2(logits = BN_pred, labels = y)
BN_loss = tf.reduce_mean(BN_loss)
update_ops = tf.get_collection(tf.GraphKeys.UPDATE_OPS)
with tf.control_dependencies(update_ops):
    BN_optm = tf.train.AdamOptimizer(lr).minimize(BN_loss)

In [ ]:
%%time

BN_init = tf.global_variables_initializer()
BN_sess = tf.Session()
BN_sess.run(BN_init)

BN_loss_record_train, BN_accr_record_train = [], []

"""
train your BN model with the normalized input
"""

for epoch in range(n_iter):
    train_x, train_y = minibatch(train_X_n, train_Y_n, n_batch)
    BN_sess.run(??, feed_dict = {x: train_x, y: train_y, is_training: True, lr: LR}) 
    
    if epoch % n_prt == 0:        

        
        
        
        BN_loss_record_train.append(BN_cost), BN_accr_record_train.append(BN_accr)
        
        print ("Iter {:05d} || train_loss: {:.4f} || train_accr: {:.2f}%".format(epoch,  BN_cost, 100*BN_accr))

In [ ]:
not_n_alpha = 0.3
n_alpha = 0.3
bn_alpha = 1

plt.figure(figsize=(10,8))
plt.plot(np.arange(len(loss_record_train))*n_prt, loss_record_train, 'k-', alpha = not_n_alpha, label = 'Not normalized')
plt.plot(np.arange(len(loss_n_record_train))*n_prt, loss_n_record_train, 'b-', alpha = n_alpha,  label = 'Normalilzed')
plt.plot(np.arange(len(BN_loss_record_train))*n_prt, BN_loss_record_train, 'r-', alpha = bn_alpha,  label = 'Norm. with BN')
plt.xlabel('Iteration', fontsize = 15)
plt.ylabel('Loss', fontsize = 15)
plt.ylim([0, 5])
plt.legend(fontsize = 12)
plt.show()
plt.figure(figsize=(10,8))
plt.plot(np.arange(len(accr_record_train))*n_prt, accr_record_train, 'k-', alpha = not_n_alpha, label = 'Not normalized')
plt.plot(np.arange(len(accr_n_record_train))*n_prt, accr_n_record_train, 'b-', alpha = n_alpha,  label = 'Normalilzed')
plt.plot(np.arange(len(BN_accr_record_train))*n_prt, BN_accr_record_train, 'r-', alpha = bn_alpha,  label = 'Norm. with BN')
plt.xlabel('Iteration', fontsize = 15)
plt.ylabel('Accuracy', fontsize = 15)
plt.legend(fontsize = 12)
plt.show()

## 3. Validation to check _"Overfitting"_

In [ ]:
%%time

sess = tf.Session()
sess.run(init)

loss_n_record_train, accr_n_record_train = [], []
loss_n_record_valid, accr_n_record_valid = [], []

"""
train and valid your base model with the normalized input
"""

for epoch in range(n_iter):
    train_x, train_y = minibatch(train_X_n, train_Y_n, n_batch)

    
    if epoch % n_prt == 0:        
        valid_x, valid_y = minibatch(valid_X_n, valid_Y_n, n_batch)

        
        
        
        
        loss_n_record_train.append(cost), accr_n_record_train.append(accr)
        loss_n_record_valid.append(cost_v), accr_n_record_valid.append(accr_v)
        
        print ("Iter {:05d} || train_loss: {:.4f} || train_accr: {:.2f}% || valid_loss: {:.4f} || valid_accr: {:.2f}%".format(epoch, 
                                                                                                                              cost, 100*accr, 
                                                                                                                              cost_v, 100*accr_v))

In [ ]:
%%time

BN_sess = tf.Session()
BN_sess.run(BN_init)

BN_loss_record_train, BN_accr_record_train = [], []
BN_loss_record_valid, BN_accr_record_valid = [], []

"""
train and valid your BN model with the normalized input
"""

for epoch in range(n_iter):
    train_x, train_y = minibatch(train_X_n, train_Y_n, n_batch)
    
    if epoch % n_prt == 0:        
        valid_x, valid_y = minibatch(valid_X_n, valid_Y_n, n_batch)
        
        
        
        
        
        
        BN_loss_record_train.append(BN_cost), BN_accr_record_train.append(BN_accr)
        BN_loss_record_valid.append(BN_cost_v), BN_accr_record_valid.append(BN_accr_v)
        
        print ("Iter {:05d} || train_loss: {:.4f} || train_accr: {:.2f}% || valid_loss: {:.4f} || valid_accr: {:.2f}%".format(epoch, 
                                                                                                                              BN_cost, 100*BN_accr, 
                                                                                                                              BN_cost_v, 100*BN_accr_v))

In [ ]:
base_alpha = 0.3
bn_alpha = 1

plt.figure(figsize=(10,8))
plt.plot(np.arange(len(loss_n_record_train))*n_prt, loss_n_record_train, 'b--', alpha = base_alpha, label = 'Base_train')
plt.plot(np.arange(len(BN_loss_record_train))*n_prt, BN_loss_record_train, 'r--', alpha = bn_alpha, label = 'BN_train')
plt.plot(np.arange(len(loss_n_record_valid))*n_prt, loss_n_record_valid, 'b-', alpha = base_alpha, label = 'Base_valid')
plt.plot(np.arange(len(BN_loss_record_valid))*n_prt, BN_loss_record_valid, 'r-', alpha = bn_alpha, label = 'BN_valid')
plt.xlabel('Iteration', fontsize = 15)
plt.ylabel('Loss', fontsize = 15)
plt.ylim([0, 5])
plt.legend(fontsize = 12)
plt.grid(alpha = 0.3)
plt.show()
plt.figure(figsize=(10,8))
plt.plot(np.arange(len(accr_n_record_train))*n_prt, accr_n_record_train, 'b--', alpha = base_alpha, label = 'Base_train')
plt.plot(np.arange(len(BN_accr_record_train))*n_prt, BN_accr_record_train, 'r--', alpha = bn_alpha, label = 'BN_train')
plt.plot(np.arange(len(accr_n_record_valid))*n_prt, accr_n_record_valid, 'b-', alpha = base_alpha, label = 'Base_valid')
plt.plot(np.arange(len(BN_accr_record_valid))*n_prt, BN_accr_record_valid, 'r-', alpha = bn_alpha, label = 'BN_valid')
plt.xlabel('Iteration', fontsize = 15)
plt.ylabel('Accuracy', fontsize = 15)
plt.legend(fontsize = 12)
plt.grid(alpha = 0.3)
plt.show()

<font size = 4>ML Tutorial: <a href="https://www.kaggle.com/tahazafar/steel-plate-faults-data-analysis" target="_blank">https://www.kaggle.com/tahazafar/steel-plate-faults-data-analysis</a></font>

In [1]:
%%javascript
$.getScript('https://kmahelona.github.io/ipython_notebook_goodies/ipython_notebook_toc.js')

<IPython.core.display.Javascript object>